name: ScriptRunner.Build.Release

on: [push]
 
jobs:
  build:
    runs-on: windows-latest
    name: Build & Release
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore .\ScriptRunner.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  .\ScriptRunner.sln -p:Configuration=Release
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Script Runner v1.0 #TODO: Use Prject version
        path: bin\Release\*
 
   
