name: ScriptRunner.Legacy.CI

on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore .\ScriptRunner.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  .\ScriptRunner.sln -p:Configuration=Release
  
  upload:
   runs-on: windows-latest
   name: 'Upload a Build Artifact'
   steps:
   - uses: actions/upload-artifact@v2
     with:
       name: release
       path: ScriptRunner\bin\Release\
